import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { ValidationPipe, VersioningType } from '@nestjs/common';
import { NestExpressApplication } from '@nestjs/platform-express';
import { Logger } from 'nestjs-pino';
import helmet from 'helmet';
import morgan from 'morgan';
import cors from 'cors';
import basicAuth from 'express-basic-auth';
import { join } from 'path';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    snapshot: true,
    bufferLogs: true,
  });

  // Setup pjino logger as default
  app.useLogger(app.get(Logger));

  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
    }),
  );

  // Protect Swagger
  app.use(
    ['/docs', '/docs/{*path}'],
    basicAuth({
      challenge: true,
      users: {
        super: 'super123',
      },
    }),
  );

  // Setup logging
  app.use(morgan('dev'));

  app.useStaticAssets(join(process.cwd(), process.env.UPLOAD_DIR || 'uploads'), {
    prefix: '/uploads/',
  });

  // Setup cors
  app.use(cors());

  // Setup security headers
  app.use(helmet());
  app.setGlobalPrefix('api');
  app.enableVersioning({
    type: VersioningType.URI,
    defaultVersion: '1',
  });

  app.useStaticAssets(join(process.cwd(), 'logs'), {
    prefix: '/logs/',
  });

  if (process.env.NODE_ENV !== 'production') {
    const config = new DocumentBuilder()
      .setTitle('Starter Docs')
      .setDescription('This swagger auto generated by nestjs')
      .setVersion('1.0')
      .addBearerAuth()
      .build();
    app.enableCors();
    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('docs', app, document);
  }

  await app.listen(process.env.PORT);
}
bootstrap();
